### ISSUE TITLE
sirf.STIR.AcquisitionDataInMemory::norm fails with VS 2019

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF#1014]
I've compiled SIRF on windows 10 with VS Community 2019 and its Python. All tests work, except `PET_TESTS_PYTHON` which gives
```
1: ERROR: tests_three.test_main
1: ----------------------------------------------------------------------
1: Traceback (most recent call last):
1:   File "C:\Users\krisf\AppData\Roaming\Python\Python37\site-packages\nose\case.py", line 198, in runTest
1:     self.test(*self.arg)
1:   File "C:\Users\krisf\Documents\devel\build\SIRF-SuperBuild\sources\SIRF\src\xSTIR\pSTIR\tests\tests_three.py", line 32, in test_main
1:     test.check(acq_data.norm())
1:   File "C:\Users\krisf\Documents\devel\install\python\sirf\Utilities.py", line 312, in check
1:     self.check_if_equal_within_tolerance(expected, value, abs_tol, rel_tol)
1:   File "C:\Users\krisf\Documents\devel\install\python\sirf\Utilities.py", line 346, in check_if_equal_within_tolerance
1:     raise ValueError(msg)
1: ValueError: +++ test 0 failed: expected 3099, got 1627 (tolerance 6.2)
```
Note that this works perfectly fine on WSL2/Ubuntu.

Digging more into this reveals that `tests_three.py` works fine when run on its own, but not if you tell `nose` to run another test first. This seems to be because `nose` runs multiple tests from one Python. So digging more, I can reproduce this by executing (Edit: corrected typos)
```Python
from sirf.STIR import *
import numpy
import numpy.linalg
data_path = examples_data_path('PET')
import tests_four
raw_data_file = existing_filepath(data_path, 'Utahscat600k_ca_seg4.hs')
acq_data = AcquisitionData(raw_data_file)
tmp=acq_data.as_array();
print(acq_data.norm()) # ->  3099.3235 (i.e. correct)
tests_four.test_main()
acq_data2 = AcquisitionData(raw_data_file)
tmp2=acq_data2.as_array();
print(numpy.max(numpy.abs(tmp-tmp2))) # -> 0 (i.e. data is identical)
print(numpy.linalg.norm(tmp2)) # -> 3099.3235 (i.e. correct)
print(acq_data2.norm()) # -> 1626.9134521484375 (i.e. wrong)
```
So , this seems a problem with `norm` only. It looks like an unitialised value somewhere, but the wrong value 1626 is perfectly reproducible...

@evgueni-ovtchinnikov do you have the same problem or not?

**Comment by evgueni-ovtchinnikov** [comment]
@KrisThielemans no, I do not get any errors - neither with `nose` nor with your test (it has a couple of typos BTW - missing bracket in the second `print` and `np` instead of `numpy`), my output is:
```
...\pSTIR\tests>python -m nose tests_three.py
Total CPU Time 2.5625secs
.
----------------------------------------------------------------------
Ran 1 test in 1.653s

OK

...\pSTIR\tests>python kt_test.py

INFO: Detected view-mashing factor 2 from the number of views (96) and the number of detectors per ring (384).
Adjusting the azimuthal angle offset accordingly (an extra offset of 0.46875 degrees)
3099.32177734375

INFO: Detected view-mashing factor 2 from the number of views (96) and the number of detectors per ring (384).
Adjusting the azimuthal angle offset accordingly (an extra offset of 0.46875 degrees)
0.0
3099.3218
3099.32177734375
```

**Comment by KrisThielemans** [comment]
ok. this is a bug.
https://github.com/SyneRBI/SIRF/blob/b5aa3994329b1cac799660cbd1e413cce211dbd0/src/xSTIR/cSTIR/include/sirf/STIR/stir_data_containers.h#L652-L653
relies on undefined order of execution. The following does work
```C++
while (iter != pd_ptr->end())
{
  t += (*iter) * (*iter);
  iter++;
}
```
This is used in other places as well (e.g. `dot`).

**Comment by KrisThielemans** [comment]
@evgueni-ovtchinnikov can you do a PR for this? (will need a line in CHANGES)
