### ISSUE TITLE
PET test_ObjectiveFunction.py can fail due to permissions (?)

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF#1034]
On our cluster system I get the following strange error
```
[kthielem@comic2 tests]$ rm -rf /SAN/inm/tools/cluster/share/SIRF-3.1/data/examples/PET/working_folder/
[kthielem@comic2 tests]$ python3 -m nose --ignore-files=test_algebra" "--exclude=TestDataContainerAlgebra --verbose test_ObjectiveFunction.py 

WARNING: Interfile parsing ended up with the following scanner:
Scanner parameters:= 
Scanner type := userdefined
Number of rings                          := 2
Number of detectors per ring             := 512
Inner ring diameter (cm)                 := 102
Average depth of interaction (cm)        := 0.7
Distance between rings (cm)              := 1.35
Default bin size (cm)                    := 0.3129
View offset (degrees)                    := 0
Maximum number of non-arc-corrected bins := 192
Default number of arc-corrected bins     := 192
Number of blocks per bucket in transaxial direction         := 1
Number of blocks per bucket in axial direction              := 1
Number of crystals per block in axial direction             := 1
Number of crystals per block in transaxial direction        := 8
Number of detector layers                                   := 1
Number of crystals per singles unit in axial direction      := 1
Number of crystals per singles unit in transaxial direction := 8
end scanner parameters:=



WARNING: Disabling symmetries as image is rotated due to phi offset of the scanner.

WARNING: Disabling symmetries as image is rotated due to phi offset of the scanner.

WARNING: forward_project. Imaging modality unknown for either the image or the projection data or both.
Going ahead anyway.

WARNING: Imaging modality is unknown for either the target or the input data or both.
Going ahead anyway.

WARNING: Disabling symmetries as image is rotated due to phi offset of the scanner.

WARNING: Disabling symmetries as image is rotated due to phi offset of the scanner.
test_Poisson_loglikelihood_call (test_ObjectiveFunction.TestSTIRObjectiveFunction) ... ERROR

======================================================================
ERROR: test_Poisson_loglikelihood_call (test_ObjectiveFunction.TestSTIRObjectiveFunction)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/SAN/inm/tools/build_cluster/SIRF-SuperBuild/Release/sources/SIRF/src/xSTIR/pSTIR/tests/test_ObjectiveFunction.py", line 36, in setUp
    shutil.copytree('thorax_single_slice','working_folder/thorax_single_slice')
  File "/share/apps/python-3.10.0-shared/lib/python3.10/shutil.py", line 556, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/share/apps/python-3.10.0-shared/lib/python3.10/shutil.py", line 457, in _copytree
    os.makedirs(dst, exist_ok=dirs_exist_ok)
  File "/share/apps/python-3.10.0-shared/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: --------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 1 test in 0.380s

FAILED (errors=1)
deleting tmp_1_1642810094360.hs failed, please delete manually
deleting tmp_1_1642810094360.s failed, please delete manually
```
checking what's in there it is not much.
```
ls -aRl /SAN/inm/tools/cluster/share/SIRF-3.1/data/examples/PET/working_folder/
/SAN/inm/tools/cluster/share/SIRF-3.1/data/examples/PET/working_folder/:
total 96
drwxrwx--- 3 kthielem inm  2048 Jan 22 00:12 .
drwxr-xr-x 6 kthielem inm 18432 Jan 22 00:12 ..
drwxr-xr-x 2 kthielem inm  2048 Jan 22 00:12 thorax_single_slice

/SAN/inm/tools/cluster/share/SIRF-3.1/data/examples/PET/working_folder/thorax_single_slice:
total 64
drwxr-xr-x 2 kthielem inm 2048 Jan 22 00:12 .
drwxrwx--- 3 kthielem inm 2048 Jan 22 00:12 ..
```
This is strange because the test is claimed to fail at the `copytree` with a `FileExists`, but
- I've deleted it first
- the reset of `SetUp` is actually running fine (so it went beyond the `copytree`), although it doesn't get into the actual test function
- I cannot find those `tmp*s` files

Possibly this is due to the temporary files problem (when are they supposed to be removed, when python exits?), but the sequence of events is completely weird to me.

**Comment by KrisThielemans** [comment]
I've checked that commenting out
https://github.com/SyneRBI/SIRF/blob/9282ce4b6c2689214b76ebf0227b75aed784a39f/src/xSTIR/pSTIR/tests/test_ObjectiveFunction.py#L52
and usage of `self.obj_fun` in `test_Poisson_loglikelihood_call` makes the problem disappear. This seems to indicate that indeed the temporary files created in the objective function are somehow causing this, but I'm still very confused.
