### ISSUE TITLE
MR_TESTS_PYTHON fails due to tolerance

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF#1071]
I get a local failure due to numerical tolerance
```
2/20 Test  #2: MR_TESTS_PYTHON .........................***Failed   18.36 sec
Started reading acquisitions from /home/sirfuser/devel/install/share/SIRF-3.1/data/examples/MR/simulated_MR_2D_cartesian.h5
0%..10%..20%..30%..40%..50%..60%..70%..80%..90%..100%..
<snip>
ERROR: test2.test_main
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/data/devel/SIRF/src/xGadgetron/pGadgetron/tests/test2.py", line 45, in test_main
    test.check(complex_images.norm() / input_norm)
  File "/home/sirfuser/devel/install/python/sirf/Utilities.py", line 312, in check
    self.check_if_equal_within_tolerance(expected, value, abs_tol, rel_tol)
  File "/home/sirfuser/devel/install/python/sirf/Utilities.py", line 346, in check_if_equal_within_tolerance
    raise ValueError(msg)
ValueError: +++ test 1 failed: expected 6.701, got 6.719 (tolerance 0.0134)
```
Seems to me we need to increase our tolerance a bit more. @johannesmayer, do you agree?

_Originally posted by @KrisThielemans in https://github.com/SyneRBI/SIRF/issues/1070#issuecomment-1066807687_

**Comment by evgueni-ovtchinnikov** [comment]
Fixed by increasing relative tolerance in test2.py first two checks to 0.01, waiting for GHA.

@KrisThielemans I suggest moving the other remaining issue to 3.3 and starting checkout for 3.2.
