### ISSUE TITLE
Travis OSX fails MR_PYTHON test

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF#580]
I noticed this first in the SuperBuild, but it's in SIRF Travis as well on @evgueni-ovtchinnikov 's https://github.com/CCPPETMR/SIRF/tree/try-merge-master, see e.g.
https://travis-ci.org/github/CCPPETMR/SIRF/jobs/662050530. References below are to the Superbuild job.

https://travis-ci.org/github/CCPPETMR/SIRF-SuperBuild/jobs/662503204#L15941 (which is the 4th OSX job, i.e. `py27 +osx +DEVEL +boost -fftw3 -hdf5 +swig`) says
```
GadgetronImagesVector::set_up_geom_info(): read_dir, phase_dir and slice_dir should all be unit vectors.
map 1 2 
map 1 2 .E.
======================================================================
ERROR: test2.test_main
---------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/travis/Library/Python/2.7/lib/python/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/travis/build/CCPPETMR/SIRF-SuperBuild/sources/SIRF/src/xGadgetron/pGadgetron/tests/test2.py", line 36, in test_main
    processed_data = input_data.process(prep_gadgets)
  File "/Users/travis/build/CCPPETMR/SIRF-SuperBuild/INSTALL/python/sirf/Gadgetron.py", line 842, in process
    return ap.process(self)
  File "/Users/travis/build/CCPPETMR/SIRF-SuperBuild/INSTALL/python/sirf/Gadgetron.py", line 1392, in process
    check_status(acquisitions.handle)
  File "/Users/travis/build/CCPPETMR/SIRF-SuperBuild/INSTALL/python/sirf/Utilities.py", line 374, in check_status
    raise error(errorMsg)
error: ??? "'write: Bad file descriptor' exception caught at line 545 of /Users/travis/build/CCPPETMR/SIRF-SuperBuild/sources/SIRF/src/xGadgetron/cGadgetron/cgadgetron.cpp; the reconstruction engine output may provide more information"
-------------------- >> begin captured stdout << ---------------------
File: /Users/travis/build/CCPPETMR/SIRF-SuperBuild/INSTALL/python/sirf/Gadgetron.py
Line: 1392
check_status found the following message sent from the engine:
--------------------- >> end captured stdout << ----------------------
```
The first bit  on `set_up_geom_info` seems the true cause. I wonder if the `write: Bad file descriptor` isn't an unrelated error in our exception processing, but I don't know really.

There's another occurrence of the `set_up_geom_info` error at https://travis-ci.org/github/CCPPETMR/SIRF-SuperBuild/jobs/662503204#L15978.

This seems really a SIRF bug.

**Comment by KrisThielemans** [comment]
This seems to have fixed itself...
